name: statsig
description: A sample command-line application.
version: 0.1.0
homepage: https://statsig.com

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  crypto: ^3.0.2
  http: ^0.13.4

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  mockito: ^5.1.0
  build_runner: ^2.1.7
  nock: 1.1.3
