name: statsig
description: Statsig SDK for Dart. Statsig enables developers to ship code faster and more safely.
version: 0.4.0
homepage: https://statsig.com

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  crypto: ^3.0.1
  http: ^1.2.1
  meta: ^1.7.0
  uuid: ^3.0.7
  simple_logger: 1.9.0+3
  hive: 2.2.3
  get_it: ^7.6.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.16.0
  mockito: ^5.1.0
  build_runner: ^2.1.7
  nock: 1.2.3
